// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$$$$$$$$$0 from "./apps/decohub.ts";
import * as $$$$$$$$$$$1 from "./apps/site.ts";
import * as $$$2 from "./loaders/extensions/productSimilarsColors.ts";
import * as $$$0 from "./loaders/Layouts/ProductCard.tsx";
import * as $$$1 from "./loaders/List/Sections.tsx";
import * as $$$3 from "./loaders/sellbie/get-auth-token.ts";
import * as $$$4 from "./loaders/sellbie/get-cashback.ts";
import * as $$$$$$0 from "./sections/Cashback/AdaptativeContent.tsx";
import * as $$$$$$1 from "./sections/Cashback/Cashback.tsx";
import * as $$$$$$2 from "./sections/Cashback/HTMLContent.tsx";
import * as $$$$$$3 from "./sections/Category/CategoryBanner.tsx";
import * as $$$$$$4 from "./sections/Category/CategoryList.tsx";
import * as $$$$$$5 from "./sections/Category/CategoryShelf.tsx";
import * as $$$$$$6 from "./sections/Content/Benefits.tsx";
import * as $$$$$$7 from "./sections/Content/CommentsSlider.tsx";
import * as $$$$$$8 from "./sections/Content/Departments.tsx";
import * as $$$$$$9 from "./sections/Content/Faq.tsx";
import * as $$$$$$10 from "./sections/Content/Form.tsx";
import * as $$$$$$11 from "./sections/Content/HighlightsBanners.tsx";
import * as $$$$$$12 from "./sections/Content/ImageAndTextHero.tsx";
import * as $$$$$$13 from "./sections/Content/InstitutionalMenu.tsx";
import * as $$$$$$14 from "./sections/Content/Logos.tsx";
import * as $$$$$$15 from "./sections/Content/OurStores.tsx";
import * as $$$$$$16 from "./sections/Content/PartnerShips.tsx";
import * as $$$$$$17 from "./sections/Content/SectionLaunch.tsx";
import * as $$$$$$18 from "./sections/Content/SectionText.tsx";
import * as $$$$$$19 from "./sections/Content/SectionTitle.tsx";
import * as $$$$$$20 from "./sections/Content/Testimonials.tsx";
import * as $$$$$$21 from "./sections/Content/TextAndImage.tsx";
import * as $$$$$$22 from "./sections/Content/TimelineSlider.tsx";
import * as $$$$$$23 from "./sections/Content/Video.tsx";
import * as $$$$$$24 from "./sections/CustomGTM.tsx";
import * as $$$$$$25 from "./sections/Footer/Footer.tsx";
import * as $$$$$$26 from "./sections/Gallery.tsx";
import * as $$$$$$27 from "./sections/Header/Header.tsx";
import * as $$$$$$28 from "./sections/Header/Topbar.tsx";
import * as $$$$$$29 from "./sections/Images/BannerGrid.tsx";
import * as $$$$$$30 from "./sections/Images/Carousel.tsx";
import * as $$$$$$31 from "./sections/Images/CarouselWithVideo.tsx";
import * as $$$$$$32 from "./sections/Images/ColectionHero.tsx";
import * as $$$$$$33 from "./sections/Images/ColectionHeroGrid.tsx";
import * as $$$$$$34 from "./sections/Images/DoubleBanners.tsx";
import * as $$$$$$35 from "./sections/Images/HeroBannerGrid.tsx";
import * as $$$$$$36 from "./sections/Images/HeroContentImage.tsx";
import * as $$$$$$37 from "./sections/Images/HeroSimple.tsx";
import * as $$$$$$38 from "./sections/Images/HeroTitleImages.tsx";
import * as $$$$$$39 from "./sections/Images/ImageGallery.tsx";
import * as $$$$$$40 from "./sections/Images/ImageTextGrid.tsx";
import * as $$$$$$41 from "./sections/Images/ImageVideo.tsx";
import * as $$$$$$42 from "./sections/Images/ImageWithCta.tsx";
import * as $$$$$$43 from "./sections/Images/OurStoresHome.tsx";
import * as $$$$$$44 from "./sections/Images/ShelfWithBanner.tsx";
import * as $$$$$$45 from "./sections/Images/ShoppableBanner.tsx";
import * as $$$$$$46 from "./sections/Images/SimpleBanner.tsx";
import * as $$$$$$47 from "./sections/Images/TextImage.tsx";
import * as $$$$$$48 from "./sections/Images/TextWithImagesSlider.tsx";
import * as $$$$$$49 from "./sections/Layout/Container.tsx";
import * as $$$$$$50 from "./sections/Layout/Flex.tsx";
import * as $$$$$$51 from "./sections/Layout/Grid.tsx";
import * as $$$$$$52 from "./sections/Layout/GridItem.tsx";
import * as $$$$$$53 from "./sections/Links/LinkTree.tsx";
import * as $$$$$$54 from "./sections/Links/Shortcuts.tsx";
import * as $$$$$$55 from "./sections/Miscellaneous/AdaptativeBenefits.tsx";
import * as $$$$$$56 from "./sections/Miscellaneous/CampaignPopup.tsx";
import * as $$$$$$57 from "./sections/Miscellaneous/CampaignTimer.tsx";
import * as $$$$$$58 from "./sections/Miscellaneous/CookieConsent.tsx";
import * as $$$$$$59 from "./sections/Miscellaneous/SellbieCashback.tsx";
import * as $$$$$$60 from "./sections/Newsletter/Newsletter.tsx";
import * as $$$$$$61 from "./sections/Newsletter/SectionNewsletter.tsx";
import * as $$$$$$62 from "./sections/Product/ImageGalleryFrontBack.tsx";
import * as $$$$$$63 from "./sections/Product/ImageGallerySlider.tsx";
import * as $$$$$$64 from "./sections/Product/NotFound.tsx";
import * as $$$$$$65 from "./sections/Product/NotFoundChallenge.tsx";
import * as $$$$$$66 from "./sections/Product/ProductDetails.tsx";
import * as $$$$$$67 from "./sections/Product/ProductInfo.tsx";
import * as $$$$$$68 from "./sections/Product/ProductMatcher.tsx";
import * as $$$$$$69 from "./sections/Product/ProductShelf.tsx";
import * as $$$$$$70 from "./sections/Product/ProductShelfTabbed.tsx";
import * as $$$$$$71 from "./sections/Product/SearchResult.tsx";
import * as $$$$$$72 from "./sections/Product/Wishlist.tsx";
import * as $$$$$$73 from "./sections/ProxyIframe.tsx";
import * as $$$$$$74 from "./sections/ReturnToTop.tsx";
import * as $$$$$$75 from "./sections/Social/InstagramPosts.tsx";
import * as $$$$$$76 from "./sections/Social/InstagramWidget.tsx";
import * as $$$$$$77 from "./sections/Social/MeetStores.tsx";
import * as $$$$$$78 from "./sections/Social/WhatsApp.tsx";
import * as $$$$$$79 from "./sections/Theme/Theme.tsx";

const manifest = {
  "loaders": {
    "site/loaders/extensions/productSimilarsColors.ts": $$$2,
    "site/loaders/Layouts/ProductCard.tsx": $$$0,
    "site/loaders/List/Sections.tsx": $$$1,
    "site/loaders/sellbie/get-auth-token.ts": $$$3,
    "site/loaders/sellbie/get-cashback.ts": $$$4,
  },
  "sections": {
    "site/sections/Cashback/AdaptativeContent.tsx": $$$$$$0,
    "site/sections/Cashback/Cashback.tsx": $$$$$$1,
    "site/sections/Cashback/HTMLContent.tsx": $$$$$$2,
    "site/sections/Category/CategoryBanner.tsx": $$$$$$3,
    "site/sections/Category/CategoryList.tsx": $$$$$$4,
    "site/sections/Category/CategoryShelf.tsx": $$$$$$5,
    "site/sections/Content/Benefits.tsx": $$$$$$6,
    "site/sections/Content/CommentsSlider.tsx": $$$$$$7,
    "site/sections/Content/Departments.tsx": $$$$$$8,
    "site/sections/Content/Faq.tsx": $$$$$$9,
    "site/sections/Content/Form.tsx": $$$$$$10,
    "site/sections/Content/HighlightsBanners.tsx": $$$$$$11,
    "site/sections/Content/ImageAndTextHero.tsx": $$$$$$12,
    "site/sections/Content/InstitutionalMenu.tsx": $$$$$$13,
    "site/sections/Content/Logos.tsx": $$$$$$14,
    "site/sections/Content/OurStores.tsx": $$$$$$15,
    "site/sections/Content/PartnerShips.tsx": $$$$$$16,
    "site/sections/Content/SectionLaunch.tsx": $$$$$$17,
    "site/sections/Content/SectionText.tsx": $$$$$$18,
    "site/sections/Content/SectionTitle.tsx": $$$$$$19,
    "site/sections/Content/Testimonials.tsx": $$$$$$20,
    "site/sections/Content/TextAndImage.tsx": $$$$$$21,
    "site/sections/Content/TimelineSlider.tsx": $$$$$$22,
    "site/sections/Content/Video.tsx": $$$$$$23,
    "site/sections/CustomGTM.tsx": $$$$$$24,
    "site/sections/Footer/Footer.tsx": $$$$$$25,
    "site/sections/Gallery.tsx": $$$$$$26,
    "site/sections/Header/Header.tsx": $$$$$$27,
    "site/sections/Header/Topbar.tsx": $$$$$$28,
    "site/sections/Images/BannerGrid.tsx": $$$$$$29,
    "site/sections/Images/Carousel.tsx": $$$$$$30,
    "site/sections/Images/CarouselWithVideo.tsx": $$$$$$31,
    "site/sections/Images/ColectionHero.tsx": $$$$$$32,
    "site/sections/Images/ColectionHeroGrid.tsx": $$$$$$33,
    "site/sections/Images/DoubleBanners.tsx": $$$$$$34,
    "site/sections/Images/HeroBannerGrid.tsx": $$$$$$35,
    "site/sections/Images/HeroContentImage.tsx": $$$$$$36,
    "site/sections/Images/HeroSimple.tsx": $$$$$$37,
    "site/sections/Images/HeroTitleImages.tsx": $$$$$$38,
    "site/sections/Images/ImageGallery.tsx": $$$$$$39,
    "site/sections/Images/ImageTextGrid.tsx": $$$$$$40,
    "site/sections/Images/ImageVideo.tsx": $$$$$$41,
    "site/sections/Images/ImageWithCta.tsx": $$$$$$42,
    "site/sections/Images/OurStoresHome.tsx": $$$$$$43,
    "site/sections/Images/ShelfWithBanner.tsx": $$$$$$44,
    "site/sections/Images/ShoppableBanner.tsx": $$$$$$45,
    "site/sections/Images/SimpleBanner.tsx": $$$$$$46,
    "site/sections/Images/TextImage.tsx": $$$$$$47,
    "site/sections/Images/TextWithImagesSlider.tsx": $$$$$$48,
    "site/sections/Layout/Container.tsx": $$$$$$49,
    "site/sections/Layout/Flex.tsx": $$$$$$50,
    "site/sections/Layout/Grid.tsx": $$$$$$51,
    "site/sections/Layout/GridItem.tsx": $$$$$$52,
    "site/sections/Links/LinkTree.tsx": $$$$$$53,
    "site/sections/Links/Shortcuts.tsx": $$$$$$54,
    "site/sections/Miscellaneous/AdaptativeBenefits.tsx": $$$$$$55,
    "site/sections/Miscellaneous/CampaignPopup.tsx": $$$$$$56,
    "site/sections/Miscellaneous/CampaignTimer.tsx": $$$$$$57,
    "site/sections/Miscellaneous/CookieConsent.tsx": $$$$$$58,
    "site/sections/Miscellaneous/SellbieCashback.tsx": $$$$$$59,
    "site/sections/Newsletter/Newsletter.tsx": $$$$$$60,
    "site/sections/Newsletter/SectionNewsletter.tsx": $$$$$$61,
    "site/sections/Product/ImageGalleryFrontBack.tsx": $$$$$$62,
    "site/sections/Product/ImageGallerySlider.tsx": $$$$$$63,
    "site/sections/Product/NotFound.tsx": $$$$$$64,
    "site/sections/Product/NotFoundChallenge.tsx": $$$$$$65,
    "site/sections/Product/ProductDetails.tsx": $$$$$$66,
    "site/sections/Product/ProductInfo.tsx": $$$$$$67,
    "site/sections/Product/ProductMatcher.tsx": $$$$$$68,
    "site/sections/Product/ProductShelf.tsx": $$$$$$69,
    "site/sections/Product/ProductShelfTabbed.tsx": $$$$$$70,
    "site/sections/Product/SearchResult.tsx": $$$$$$71,
    "site/sections/Product/Wishlist.tsx": $$$$$$72,
    "site/sections/ProxyIframe.tsx": $$$$$$73,
    "site/sections/ReturnToTop.tsx": $$$$$$74,
    "site/sections/Social/InstagramPosts.tsx": $$$$$$75,
    "site/sections/Social/InstagramWidget.tsx": $$$$$$76,
    "site/sections/Social/MeetStores.tsx": $$$$$$77,
    "site/sections/Social/WhatsApp.tsx": $$$$$$78,
    "site/sections/Theme/Theme.tsx": $$$$$$79,
  },
  "apps": {
    "site/apps/decohub.ts": $$$$$$$$$$$0,
    "site/apps/site.ts": $$$$$$$$$$$1,
  },
  "name": "site",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
